version: '2'
volumes:
  mysql_data:
services:
  apache-ps:
    container_name: ps_apache
    build: ./apache
    ports:
      - 8089:80
    volumes:
      - ./html:/var/www/html
    restart: always
    ulimits:
      stack: -1
    environment:
      - CRON_INTERVAL_SEC=60
      - SMTP_MAILHUB=smtp.yandex.ru:465
      - SMTP_USER=server@pdd-host.ru
      - SMTP_PASS=password
      - SMTP_REWRITE_DOMAIN=pdd-host.ru
      - SMTP_HOSTNAME=www.host.ru
  mysql-s:
    container_name: ps_mysql
    build: ./mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password2
    restart: always
    ports:
      - 33088:3306
